# 读写文件
保存训练的模型，以备将来在各种环境中使用（比如在部署中进行预测），即学习如何加载和存储权重向量和整个模型。

## 加载和保存张量
对于单个张量，可以直接调用`load`和`save`函数分别读写它们。

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

# save要求将要保存的变量作为输入
x = torch.arange(4)
torch.save(x, 'x-file')
# load
x2 = torch.load('x-file')
print(x2)

tensor([0, 1, 2, 3])


存储一个张量列表，然后把它们读回内存。

In [2]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

写入或读取从字符串映射到张量的字典。

In [3]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 加载和保存模型参数
**需要原始模型MLP()和存储参数的文件**，主要函数：**net.state_dict()** 和 **net.load_state_dict()**

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

X = torch.randn(size=(2, 20))
net = MLP()
Y = net(X)

torch.save(net.state_dict(), 'mlp.params')

clone_net = MLP()
clone_net.load_state_dict(torch.load('mlp.params'))
clone_net.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [6]:
Y_clone = clone_net(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])